import { GpuEffectSettings } from '../types/editor';

export interface GpuPreset {
  id: string;
  name: string;
  category: 'filter' | 'particle';
  icon: string;
  description: string;
  duration: number; // default duration in seconds
  color: string; // theme color
  settings: GpuEffectSettings;
}

export const GPU_FILTER_PRESETS: GpuPreset[] = [
  {
    id: 'filter-glitch',
    name: '故障风 (Glitch & RGB Shift)',
    category: 'filter',
    icon: '⚡',
    description: '画面横向撕裂、信号抖动与色差故障',
    duration: 3,
    color: '#06b6d4',
    settings: {
      category: 'filter',
      filterType: 'glitch',
      intensity: 65,
      speed: 1.2,
      frequency: 1.5,
      name: '故障风 (Glitch)',
    },
  },
  {
    id: 'filter-bloom',
    name: '霓虹发光 (Neon Bloom & Glow)',
    category: 'filter',
    icon: '✨',
    description: '电影级高亮泛光与柔和霓虹光晕',
    duration: 5,
    color: '#ec4899',
    settings: {
      category: 'filter',
      filterType: 'bloom',
      intensity: 70,
      speed: 1.0,
      color: '#ff007f',
      name: '霓虹发光 (Bloom)',
    },
  },
  {
    id: 'filter-shockwave',
    name: '水波冲击 (Shockwave Ripple)',
    category: 'filter',
    icon: '🌊',
    description: '中心向外扩散的动态折射水波与震荡冲击',
    duration: 3,
    color: '#3b82f6',
    settings: {
      category: 'filter',
      filterType: 'shockwave',
      intensity: 80,
      speed: 1.0,
      frequency: 1.0,
      name: '水波冲击 (Shockwave)',
    },
  },
  {
    id: 'filter-rgb-split',
    name: 'RGB 色差分离 (Chromatic Split)',
    category: 'filter',
    icon: '🔴',
    description: '红蓝绿三原色边缘分离错位视觉',
    duration: 4,
    color: '#a855f7',
    settings: {
      category: 'filter',
      filterType: 'rgbSplit',
      intensity: 60,
      speed: 1.0,
      name: 'RGB 分离 (RGB Split)',
    },
  },
  {
    id: 'filter-crt',
    name: '复古 CRT 电视 (Retro Scanlines)',
    category: 'filter',
    icon: '📺',
    description: '80年代显像管扫描线与暗角噪点',
    duration: 6,
    color: '#eab308',
    settings: {
      category: 'filter',
      filterType: 'crt',
      intensity: 50,
      speed: 1.0,
      name: '复古 CRT 电视',
    },
  },
  {
    id: 'filter-radial-blur',
    name: '径向放射模糊 (Radial Zoom)',
    category: 'filter',
    icon: '🌀',
    description: '中心向四周爆发的动态放射速度感',
    duration: 3,
    color: '#10b981',
    settings: {
      category: 'filter',
      filterType: 'radialBlur',
      intensity: 55,
      speed: 1.0,
      name: '径向放射模糊',
    },
  },
];

export const GPU_PARTICLE_PRESETS: GpuPreset[] = [
  {
    id: 'particle-snow',
    name: '浪漫飘雪 (Romantic Snow)',
    category: 'particle',
    icon: '❄️',
    description: '晶莹雪花随风摇曳缓缓飘落，景深层次丰富',
    duration: 8,
    color: '#93c5fd',
    settings: {
      category: 'particle',
      particleType: 'snow',
      intensity: 60,
      speed: 1.0,
      density: 1.2,
      size: 1.0,
      color: '#ffffff',
      blendMode: 'screen',
      name: '浪漫飘雪 (Snow)',
    },
  },
  {
    id: 'particle-gold-dust',
    name: '金粉雨 (Golden Stardust)',
    category: 'particle',
    icon: '✨',
    description: '璀璨金光尘埃漂浮升腾，闪烁微光轨迹',
    duration: 6,
    color: '#fbbf24',
    settings: {
      category: 'particle',
      particleType: 'goldDust',
      intensity: 75,
      speed: 0.8,
      density: 1.5,
      size: 1.2,
      color: '#ffd700',
      blendMode: 'add',
      name: '金粉雨 (Golden Dust)',
    },
  },
  {
    id: 'particle-fire-sparks',
    name: '火焰火星 (Fire Sparks)',
    category: 'particle',
    icon: '🔥',
    description: '炙热火星升腾飞舞，逐渐冷却暗化',
    duration: 5,
    color: '#f97316',
    settings: {
      category: 'particle',
      particleType: 'fireSparks',
      intensity: 80,
      speed: 1.4,
      density: 1.3,
      size: 1.1,
      color: '#ff4500',
      blendMode: 'add',
      name: '火焰火花 (Sparks)',
    },
  },
  {
    id: 'particle-cyber-bokeh',
    name: '赛博光斑 (Cyberpunk Bokeh)',
    category: 'particle',
    icon: '🔮',
    description: '霓虹多边形光斑虚化交织，梦幻漂浮',
    duration: 7,
    color: '#d946ef',
    settings: {
      category: 'particle',
      particleType: 'cyberBokeh',
      intensity: 70,
      speed: 0.7,
      density: 0.9,
      size: 1.5,
      color: '#00ffff',
      blendMode: 'screen',
      name: '赛博光斑 (Cyber Bokeh)',
    },
  },
  {
    id: 'particle-meteor-shower',
    name: '流星雨 (Meteor Shower)',
    category: 'particle',
    icon: '🌠',
    description: '划破夜空的耀眼流星，附带流光尾迹',
    duration: 6,
    color: '#38bdf8',
    settings: {
      category: 'particle',
      particleType: 'meteorShower',
      intensity: 85,
      speed: 1.8,
      density: 1.0,
      size: 1.2,
      color: '#67e8f9',
      blendMode: 'add',
      name: '流星雨 (Meteors)',
    },
  },
  {
    id: 'particle-matrix-rain',
    name: '数码代码雨 (Matrix Rain)',
    category: 'particle',
    icon: '💻',
    description: '黑客帝国荧光绿代码瀑布倾泻',
    duration: 6,
    color: '#22c55e',
    settings: {
      category: 'particle',
      particleType: 'matrixRain',
      intensity: 75,
      speed: 1.2,
      density: 1.4,
      size: 1.0,
      color: '#00ff66',
      blendMode: 'screen',
      name: '数码代码雨 (Matrix)',
    },
  },
  {
    id: 'particle-sakura',
    name: '落樱缤纷 (Sakura Petals)',
    category: 'particle',
    icon: '🌸',
    description: '粉色樱花瓣在微风中盘旋下落',
    duration: 8,
    color: '#f472b6',
    settings: {
      category: 'particle',
      particleType: 'sakura',
      intensity: 65,
      speed: 0.9,
      density: 1.1,
      size: 1.1,
      color: '#ffb7c5',
      blendMode: 'normal',
      name: '落樱缤纷 (Sakura)',
    },
  },
];
