import {
  AspectRatio,
  Resolution,
  TextSettings,
  ColorFilter,
  Transform,
  AudioSettings,
  ColorGrading,
  EqualizerSettings,
  CompressorSettings,
} from '../types/editor';

export const ASPECT_RATIOS: Record<AspectRatio, Resolution> = {
  '16:9': { width: 1920, height: 1080, label: '16:9 宽屏 (YouTube / 橫屏)', aspectRatio: '16:9' },
  '9:16': { width: 1080, height: 1920, label: '9:16 竖屏 (抖音 / TikTok / Reels)', aspectRatio: '9:16' },
  '1:1': { width: 1080, height: 1080, label: '1:1 正方形 (Instagram / 帖子)', aspectRatio: '1:1' },
  '4:5': { width: 1080, height: 1350, label: '4:5 肖像 (小红书 / 社媒)', aspectRatio: '4:5' },
  '21:9': { width: 2560, height: 1080, label: '21:9 电影宽画幅 (Cinematic)', aspectRatio: '21:9' },
};

export const DEFAULT_TRANSFORM: Transform = {
  x: 0,
  y: 0,
  scale: 1,
  rotation: 0,
  opacity: 1,
  zIndex: 1,
  flipH: false,
  flipV: false,
};

export const DEFAULT_FILTER: ColorFilter = {
  brightness: 100,
  contrast: 100,
  saturate: 100,
  blur: 0,
  hueRotate: 0,
  sepia: 0,
  grayscale: 0,
  vignette: 0,
  temperature: 0,
};

export const DEFAULT_COLOR_GRADING: ColorGrading = {
  enabled: false,
  lift: { r: 0, g: 0, b: 0, y: 0 },
  gamma: { r: 0, g: 0, b: 0, y: 0 },
  gain: { r: 0, g: 0, b: 0, y: 0 },
  offset: { r: 0, g: 0, b: 0, y: 0 },
  temperature: 0,
  tint: 0,
  exposure: 0,
  contrast: 100,
  saturation: 100,
  vibrance: 0,
  curves: {
    master: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
    red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
    green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
    blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
  },
};

export const DEFAULT_EQUALIZER: EqualizerSettings = {
  enabled: false,
  lowGain: 0,
  lowFreq: 100,
  midGain: 0,
  midFreq: 1000,
  highGain: 0,
  highFreq: 8000,
};

export const DEFAULT_COMPRESSOR: CompressorSettings = {
  enabled: false,
  threshold: -24,
  ratio: 4,
  attack: 0.003,
  release: 0.25,
  knee: 30,
};

export const DEFAULT_AUDIO: AudioSettings = {
  volume: 1,
  fadeIn: 0,
  fadeOut: 0,
  muted: false,
  pan: 0,
  equalizer: DEFAULT_EQUALIZER,
  compressor: DEFAULT_COMPRESSOR,
};

export const DEFAULT_TEXT: TextSettings = {
  text: '双击编辑文字',
  fontFamily: 'Inter, system-ui, sans-serif',
  fontSize: 48,
  fontWeight: 'bold',
  fontStyle: 'normal',
  color: '#FFFFFF',
  strokeColor: '#000000',
  strokeWidth: 3,
  bgColor: 'rgba(0, 0, 0, 0.4)',
  bgPadding: 16,
  bgRadius: 8,
  align: 'center',
  shadowColor: 'rgba(0, 0, 0, 0.8)',
  shadowBlur: 10,
  shadowOffsetX: 2,
  shadowOffsetY: 4,
  animation: 'none',
  letterSpacing: 1,
  lineHeight: 1.2,
};

// Curated stock video clips (Public domain reliable video sources + auto fallbacks)
export const SAMPLE_VIDEOS = [
  {
    id: 'sample-v1',
    name: '赛博朋克夜市 (Cyberpunk City)',
    category: 'City',
    duration: 12,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=400&auto=format&fit=crop&q=80',
    type: 'video' as const,
  },
  {
    id: 'sample-v2',
    name: '唯美自然风光 (Nature Forest)',
    category: 'Nature',
    duration: 15,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&auto=format&fit=crop&q=80',
    type: 'video' as const,
  },
  {
    id: 'sample-v3',
    name: '科技代码流 (Coding Stream)',
    category: 'Tech',
    duration: 10,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80',
    type: 'video' as const,
  },
  {
    id: 'sample-v4',
    name: '极简流光动画 (Abstract Motion)',
    category: 'Abstract',
    duration: 14,
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&auto=format&fit=crop&q=80',
    type: 'video' as const,
  },
];

// Sample Stock Images & Overlays
export const SAMPLE_IMAGES = [
  {
    id: 'sample-img1',
    name: '落日晚霞 (Golden Sunset)',
    category: 'Landscape',
    duration: 5,
    url: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1200&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=300&auto=format&fit=crop&q=80',
    type: 'image' as const,
  },
  {
    id: 'sample-img2',
    name: '城市天际线 (City Skyline)',
    category: 'City',
    duration: 5,
    url: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=1200&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=300&auto=format&fit=crop&q=80',
    type: 'image' as const,
  },
  {
    id: 'sample-img3',
    name: '极光星空 (Aurora Night)',
    category: 'Nature',
    duration: 5,
    url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&auto=format&fit=crop&q=80',
    thumbnail: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=300&auto=format&fit=crop&q=80',
    type: 'image' as const,
  },
];

// Curated Royalty-free Audio & SFX Presets
export const SAMPLE_AUDIOS = [
  {
    id: 'sample-a1',
    name: '轻快Vlog节奏 (Upbeat Vlog Beats)',
    category: 'BGM',
    duration: 20,
    toneType: 'upbeat',
    type: 'audio' as const,
  },
  {
    id: 'sample-a2',
    name: '电影感史诗氛围 (Cinematic Ambient)',
    category: 'BGM',
    duration: 24,
    toneType: 'cinematic',
    type: 'audio' as const,
  },
  {
    id: 'sample-a3',
    name: '赛博电子波 (Cyber Synthwave)',
    category: 'BGM',
    duration: 18,
    toneType: 'synthwave',
    type: 'audio' as const,
  },
  {
    id: 'sample-a4',
    name: 'Lo-Fi 温暖午后 (Lo-Fi Chill)',
    category: 'BGM',
    duration: 22,
    toneType: 'lofi',
    type: 'audio' as const,
  },
  // Sound Effects
  {
    id: 'sample-sfx1',
    name: '呼啸转场 (Whoosh Swish)',
    category: 'SFX',
    duration: 1.2,
    toneType: 'sfx-whoosh',
    type: 'audio' as const,
  },
  {
    id: 'sample-sfx2',
    name: '气泡弹出 (Pop Bubble)',
    category: 'SFX',
    duration: 0.6,
    toneType: 'sfx-pop',
    type: 'audio' as const,
  },
  {
    id: 'sample-sfx3',
    name: '清脆提示音 (Success Ding)',
    category: 'SFX',
    duration: 1.0,
    toneType: 'sfx-ding',
    type: 'audio' as const,
  },
  {
    id: 'sample-sfx4',
    name: '电子故障音 (Digital Glitch)',
    category: 'SFX',
    duration: 0.8,
    toneType: 'sfx-glitch',
    type: 'audio' as const,
  },
];

// Text Templates
export const TEXT_TEMPLATES = [
  {
    id: 'tpl-headline',
    name: '冲击力大标题 (Bold Headline)',
    category: 'Title',
    config: {
      text: '🔥 震撼大标题',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      fontSize: 64,
      fontWeight: '800' as const,
      fontStyle: 'normal' as const,
      color: '#FFE600',
      strokeColor: '#000000',
      strokeWidth: 5,
      bgColor: 'transparent',
      bgPadding: 0,
      bgRadius: 0,
      align: 'center' as const,
      shadowColor: 'rgba(0,0,0,0.9)',
      shadowBlur: 14,
      shadowOffsetX: 3,
      shadowOffsetY: 6,
      animation: 'pop' as const,
      letterSpacing: 2,
      lineHeight: 1.2,
    },
  },
  {
    id: 'tpl-neon',
    name: '霓虹发光文字 (Neon Cyberpunk)',
    category: 'Title',
    config: {
      text: '⚡ CYBERPUNK 2088',
      fontFamily: 'Courier New, monospace',
      fontSize: 54,
      fontWeight: 'bold' as const,
      fontStyle: 'normal' as const,
      color: '#00FFFF',
      strokeColor: '#FF007F',
      strokeWidth: 2,
      bgColor: 'rgba(10, 10, 25, 0.7)',
      bgPadding: 16,
      bgRadius: 8,
      align: 'center' as const,
      shadowColor: '#00FFFF',
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      animation: 'neon-pulse' as const,
      letterSpacing: 4,
      lineHeight: 1.2,
    },
  },
  {
    id: 'tpl-sub-box',
    name: 'Vlog 黑底字幕条 (Vlog Subtitle Box)',
    category: 'Subtitle',
    config: {
      text: '这是一个清晰优雅的 Vlog 字幕条',
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: 38,
      fontWeight: '600' as const,
      fontStyle: 'normal' as const,
      color: '#FFFFFF',
      strokeColor: 'transparent',
      strokeWidth: 0,
      bgColor: 'rgba(0, 0, 0, 0.75)',
      bgPadding: 14,
      bgRadius: 8,
      align: 'center' as const,
      shadowColor: 'rgba(0,0,0,0.5)',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      animation: 'slide-up' as const,
      letterSpacing: 1,
      lineHeight: 1.3,
    },
  },
  {
    id: 'tpl-typewriter',
    name: '打字机效果 (Typewriter Story)',
    category: 'Story',
    config: {
      text: '“故事往往从一个不经意的瞬间开始…”',
      fontFamily: 'Georgia, serif',
      fontSize: 42,
      fontWeight: 'normal' as const,
      fontStyle: 'italic' as const,
      color: '#F3E8FF',
      strokeColor: '#2E1065',
      strokeWidth: 2,
      bgColor: 'rgba(23, 15, 38, 0.65)',
      bgPadding: 18,
      bgRadius: 10,
      align: 'center' as const,
      shadowColor: 'rgba(0,0,0,0.8)',
      shadowBlur: 10,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      animation: 'typewriter' as const,
      letterSpacing: 2,
      lineHeight: 1.4,
    },
  },
  {
    id: 'tpl-badge',
    name: '社交媒体关注角标 (Follow / Subscribe)',
    category: 'Badge',
    config: {
      text: '👉 点击关注 @OpenCut 剪辑',
      fontFamily: 'system-ui, sans-serif',
      fontSize: 36,
      fontWeight: 'bold' as const,
      fontStyle: 'normal' as const,
      color: '#FFFFFF',
      strokeColor: 'transparent',
      strokeWidth: 0,
      bgColor: '#EF4444',
      bgPadding: 14,
      bgRadius: 24,
      align: 'center' as const,
      shadowColor: 'rgba(239, 68, 68, 0.4)',
      shadowBlur: 12,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      animation: 'bounce' as const,
      letterSpacing: 1,
      lineHeight: 1.2,
    },
  },
];

// Color Filter Presets
export const FILTER_PRESETS = [
  {
    id: 'filter-normal',
    name: '原画质 (Original)',
    filter: { ...DEFAULT_FILTER },
  },
  {
    id: 'filter-teal-orange',
    name: '青橙电影色 (Teal & Orange)',
    filter: {
      brightness: 105,
      contrast: 120,
      saturate: 130,
      blur: 0,
      hueRotate: 15,
      sepia: 20,
      grayscale: 0,
      vignette: 25,
      temperature: 15,
    },
  },
  {
    id: 'filter-vintage',
    name: '复古胶片 (Vintage Film)',
    filter: {
      brightness: 95,
      contrast: 110,
      saturate: 85,
      blur: 0,
      hueRotate: -10,
      sepia: 40,
      grayscale: 0,
      vignette: 35,
      temperature: 25,
    },
  },
  {
    id: 'filter-noir',
    name: '黑白胶片 (Noir B&W)',
    filter: {
      brightness: 100,
      contrast: 135,
      saturate: 0,
      blur: 0,
      hueRotate: 0,
      sepia: 0,
      grayscale: 100,
      vignette: 40,
      temperature: 0,
    },
  },
  {
    id: 'filter-cyberpunk',
    name: '赛博霓虹 (Cyber Neon)',
    filter: {
      brightness: 110,
      contrast: 140,
      saturate: 160,
      blur: 0,
      hueRotate: 290,
      sepia: 10,
      grayscale: 0,
      vignette: 30,
      temperature: -20,
    },
  },
  {
    id: 'filter-sunset',
    name: '暖阳落日 (Warm Sunset)',
    filter: {
      brightness: 108,
      contrast: 115,
      saturate: 140,
      blur: 0,
      hueRotate: 345,
      sepia: 25,
      grayscale: 0,
      vignette: 15,
      temperature: 40,
    },
  },
  {
    id: 'filter-crisp-hdr',
    name: '清晰通透 HDR (Crisp HDR)',
    filter: {
      brightness: 105,
      contrast: 125,
      saturate: 120,
      blur: 0,
      hueRotate: 0,
      sepia: 0,
      grayscale: 0,
      vignette: 10,
      temperature: 0,
    },
  },
];

// Sticker and Emoji catalog
export const STICKER_LIST = [
  { id: 'stk-1', emoji: '🔥', name: '爆款火焰' },
  { id: 'stk-2', emoji: '✨', name: '闪烁高光' },
  { id: 'stk-3', emoji: '🎬', name: '电影场记板' },
  { id: 'stk-4', emoji: '💯', name: '满分好评' },
  { id: 'stk-5', emoji: '⚡', name: '闪电高能' },
  { id: 'stk-6', emoji: '💥', name: '爆炸冲击' },
  { id: 'stk-7', emoji: '🎉', name: '庆祝彩带' },
  { id: 'stk-8', emoji: '👀', name: '注意看' },
  { id: 'stk-9', emoji: '👇', name: '下方向指引' },
  { id: 'stk-10', emoji: '❤️', name: '一键三连' },
  { id: 'stk-11', emoji: '🚀', name: '火箭起飞' },
  { id: 'stk-12', emoji: '🎯', name: '直中要害' },
  { id: 'stk-13', emoji: '💡', name: '干货灵感' },
  { id: 'stk-14', emoji: '⭐', name: '五星推荐' },
  { id: 'stk-15', emoji: '⏱️', name: '倒计时' },
  { id: 'stk-16', emoji: '🎙️', name: '正在录音' },
];
